config/routes.rb
Fantees::Application.routes.draw do
  root :to => 'home#index'

  devise_for :users, :skip => [:registrations]

  get "dashboard", :controller => 'dashboard/home', :action => :index
  namespace :dashboard do
    resources :users, :only => [:show, :update]
    resources :giftcards, :only => [:index, :show ]
    resources :orders, :only => [:index, :show, :update] do

      member do
        get :ordered_products
      end
      collection do
        get :latest
      end
    end
  end

  resources :products, :only => [:index, :show] do
    collection do
      get  :checkout
      post :set_checkout_session
      post :paypal_checkout
      post :eway_checkout
      post :order_checkout
      get  "api/:slug", :action => :product_info
      get  "upsell/:key", :action => :product_upsell
      # get :success, :action => :return_url
    end
    member do
      get :success, :action => :return_url
    end
  end
  # get "product_info/:slug", :controller => :products, :action => :product_info
  get "products/:id/:url", :controller => "products", :action => :show

  resources :categories, :only => [:index, :show]
  resources :orders, :only => [:show, :create] do
    member do
      get :success, :action => :show
    end
    collection do
      post :update_unfinished, :action => :update_unfinished_order
    end
  end
  get "order/rebuild/:tracking_id", :controller => :orders, :action => :rebuild

  # checkout pages
  resources :cart, :only => [:index, :create, :update, :destroy] do
    collection do
      get :all
      get :creditcard
      get :paypal_express
      get :checkout
      post :checkout
      get :giftcards
      post :giftcard_express

    end
  end
  get "cart/rebuild/:tracking_id", :controller => :cart, :action => :rebuild

  post "pages/send_contact_us"
  get "contact-us",           :controller => :pages, :action => :contact_us
  get "about-us",             :controller => :pages, :action => :about_us
  get "faq",                  :controller => :pages, :action => :faq
  get "privacy-policy",       :controller => :pages, :action => :privacy
  get "terms-of-service",     :controller => :pages, :action => :terms
  get "shipping",             :controller => :pages, :action => :shipping
  get "returns-exchanges",    :controller => :pages, :action => :returns_exchanges
  get "sizing",               :controller => :pages, :action => :sizing
  get "process",              :controller => :pages, :action => :processing
  get "pinterest-56764.html", :controller => :pages, :action => :pinterest
  get "win",                  :controller => :pages, :action => :win
  get "coupons/:code",        :controller => :coupons, :action => :show
  get "giftcards/:code",      :controller => :giftcards, :action => :show
  get "bundle",               :controller => :home, :action => :bundled
  get "giftcards",            :controller => :home, :action => :giftcards
  get "home/search",               :controller => :home, :action => :search
  get "search/name",          :controller => :products, :action => :name_search
  post "search/name/notify",  :controller => :products, :action => :name_search_notify

  get "render_email_pixel/:time_frame",   :controller => :mail_tracker, :action => :render_pixel, :as => :render_email_pixel

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'f@nt33s'
  end
  mount Sidekiq::Web => '/sidekiq'

  get "fathersday",           :controller => :home, :action => :custom_url
  get "pet-rescue",           :controller => :home, :action => :custom_url
  get "fishing-shirts",       :controller => :home, :action => :fishing_shirts
  get "nurse-shirts",         :controller => :home, :action => :nurse_shirts
  get "mechanic-shirts",      :controller => :home, :action => :mechanic_shirts
  get "sprint-car-shirts",    :controller => :home, :action => :sprint_car_shirts
  get "firefighter-shirts",   :controller => :home, :action => :firefighter_shirts
  get "dog-shirts",           :controller => :home, :action => :dog_shirts
  get "builder-shirts",       :controller => :home, :action => :builder_shirts
  get "electrician-shirts",   :controller => :home, :action => :electrician_shirts
  get "dirt-bike-shirts",     :controller => :home, :action => :dirt_bike_shirts
  get "british-comedy-shirts",:controller => :home, :action => :british_comedy_shirts
  get "beard-shirts",         :controller => :home, :action => :beard_shirts
  get "drag-racing-shirts",   :controller => :home, :action => :drag_racing_shirts
  get "camping-shirts",       :controller => :home, :action => :camping_shirts
  get "football-shirts",      :controller => :home, :action => :football_shirts
  get "torana-shirts",        :controller => :home, :action => :torana_shirts
  get "rum-shirts",           :controller => :home, :action => :rum_shirts
  get "wine-shirts",          :controller => :home, :action => :wine_shirts
  get "v8-shirts",            :controller => :home, :action => :v8_shirts
  get "army-shirts",          :controller => :home, :action => :army_shirts
  get "burnout-shirts",       :controller => :home, :action => :burnout_shirts
  get "farmanimalrescue",     :controller => :home, :action => :farmanimalrescue_shirts

  get ":slug",                :controller => "products", :action => :show
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  layout "products"
  def index
    session.delete(:coupon)
    session.delete(:giftcard)

    @order          = Order.new
    @errors         = []
    gon.website     = @website
    @title          = "Cart | FanTees"
    @has_giftcards  = false
    # gon.order   = order_fields
    # gon.payment = "PP"

    unfinished_orders unless session[:rebuild]
  end

  def creditcard
    if giftcard_total_zero() == true
      redirect_to giftcards_cart_index_path
    else
      @order      = Order.new
      @errors     = []
      gon.website = @website
      gon.order   = order_fields
      gon.payment = "PP"
      gon.coupon  = Coupon.find_by_code session[:coupon]
      gon.giftcard  = Giftcard.find_by_key_code session[:giftcard]
      @title      = "Secure Checkout | FanTees"
    end
    # render :json => session
  end

  def rebuild
    order = UnfinishedOrder.find_by_tracking_id(params[:tracking_id])

    # add mail tracker for email clicks
    if params[:time_frame]
      case params[:time_frame]
      when "30m"
        time_frame = "30-minutes"
      when "1d"
        time_frame = "1-day"
      when "10d"
        time_frame = "10-days"
      end
      MailTracker.increment_count("click", time_frame)
      session[:rebuild_time_frame] = time_frame
    end

    # check if order is this available
    if order.nil?
      redirect_to root_url
    else
      # rebuild the cart here
      cart_items = []
      order.settings(:cart).items.each do |item|
        product = Product.find(item[:product_id])
        if product.active
          cart_items.push item
        end
      end

      @cart.delete_all

      @cart.create cart_items
      session[:unfinished_order_tracking_id] = order.tracking_id

      session[:rebuild] = true

      # redirect here
      redirect_to cart_index_url
    end
  end

  def create
    @cart.create params[:cart][:items]
    render :json => {items: @cart.all}
  end

  def update
    @cart.update_attributes(params[:id], params[:cart])
    items = @cart.all
    render :json => {items: items, shipping: @cart.shipping_fee, delivery_date: @cart.delivery_date, total_qty: @cart.quantity}
  end

  def destroy
    @cart.delete params[:id]
    items = @cart.all
    render :json => {items: items, shipping: @cart.shipping_fee, delivery_date: @cart.delivery_date, total_qty: @cart.quantity}
  end

  def all
    items = @cart.all
    begin
      unfinished_order              = UnfinishedOrder.find_by_tracking_id(session[:unfinished_order_tracking_id])
      unfinished_cart               = unfinished_order.settings(:cart)
      checkout_details              = {}
      checkout_details[:email]      = unfinished_cart.user_email
      checkout_details[:first_name] = unfinished_cart.first_name
      checkout_details[:last_name]  = unfinished_cart.last_name
      checkout_details[:address]    = unfinished_cart.address
      checkout_details[:town]       = unfinished_cart.town
      checkout_details[:state]      = unfinished_cart.state
      checkout_details[:postal]     = unfinished_cart.postal
      checkout_details[:country]    = unfinished_cart.country
      checkout_details[:phone]      = unfinished_cart.phone
    rescue
      checkout_details = {}
    end

    render :json => {unfinished_order: checkout_details, items: items, shipping: @cart.shipping_fee, delivery_date: @cart.delivery_date, total_qty: @cart.quantity}
  end

  def checkout
    unless session[:items].count > 0
      redirect_to cart_index_path
    else
      order       = get_order(params)
      @order      = Order.new(order)
      gon.website = @website
      # gon.order   = params[:order]
      gon.payment = params[:payment]
      if giftcard_total_zero() == true
        redirect_to giftcards_cart_index_path
      else
        if params[:payment] == "PP"
          express_paypal
        else
          # render :json => order
          eway_creditcard
        end
      end
    end
  end

  def paypal_express
    unless session[:items].nil? && session['_csrf_token'] == params[:session_token]
      order  = get_order
      @order = Order.new(order)
      cart   = @order.cart

      if cart.errors.empty?
        order  = cart.create_user_and_order(params, request.remote_ip, false)

        if order
          response = cart.paypal_purchase?(
            :ip       => request.remote_ip,
            :token    => params["token"],
            :payer_id => params["PayerID"]
          )

          if response == true
            update_coupon_usage if session[:coupon]
            if session[:giftcard]
              totalAmount = 0
              session[:items].each do |i|
                totalAmount += i[:price].to_f
              end
              update_giftcard_usage(totalAmount, cart.get_user.id)
            end
            # send mail
            if @has_giftcards == true
              UserMailer.on_purchase_giftcard(order.id, cart.get_order.items, cart.get_password).deliver
            else
              UserMailer.on_purchase(order.id, cart.get_order.items, cart.get_password).deliver
            end

            session.delete(:coupon)
            session.delete(:giftcard)
            session.delete(:order)
            @cart.delete_all

            sign_in(:user, cart.get_user)
            # order.send_order_mail(cart.get_password)

            redirect_to order_url(order.order_id)
          else
            cart.delete_order
            redirect_to cart_index_path(:error => true)
          end
        end
      else
        @errors = cart.errors
        render "index"
      end
    else
      redirect_to cart_index_path(:error => true)
    end
  end

  def giftcards
    if giftcard_total_zero() == true
      @order      = Order.new
      @errors     = []
      gon.website = @website
      gon.order   = order_fields
      gon.payment = "PP"
      gon.coupon  = Coupon.find_by_code session[:coupon]
      gon.giftcard  = Giftcard.find_by_key_code session[:giftcard]
      @title      = "Secure Checkout | FanTees"
    else
      redirect_to cart_index_path
    end
  end

  def giftcard_express
    if giftcard_total_zero() == true
      order  = get_order
      @order = Order.new(order)
      cart   = @order.cart

      cart  = @order.cart
      order = params[:order]
      order.delete(:cc_number)
      order.delete(:cvn)


      if cart.errors.empty?
        order  = cart.gc_create_user_and_order(params[:order], request.remote_ip)

        if session[:giftcard]
          totalAmount = 0
          session[:items].each do |i|
            totalAmount += i[:price].to_f
          end
          update_giftcard_usage(totalAmount, cart.get_user.id)
        end
        # send mail
        if @has_giftcards == true
          UserMailer.on_purchase_giftcard(order.id, cart.get_order.items, cart.get_password).deliver
        else
          UserMailer.on_purchase(order.id, cart.get_order.items, cart.get_password).deliver
        end

        session.delete(:coupon)
        session.delete(:giftcard)
        session.delete(:order)
        @cart.delete_all

        sign_in(:user, cart.get_user)
        redirect_to order_url(order.order_id)
      end
    else
      redirect_to cart_index_path
    end


  end

  private

  def get_order(params = {})
    order = {}
    order[:items]   = []
    order[:coupon_code] = session[:coupon] unless session[:coupon].blank?
    order[:giftcard_code] = session[:giftcard] unless session[:giftcard].blank?
    session[:items].each do |i|
      product = Product.find(i[:product_id])
      @has_giftcards = product.gift_card == true ? true : false
      order[:items] << {product_id: i[:product_id], category_id: i[:category_id], quantity: i[:quantity], size: i[:size], price: i[:price]}
    end

    order = params[:order].reverse_merge(order) unless params[:order].blank?
    order[:country] = @website.name == "FanTees-NZ" ? "NZ" : "AU" if order[:country].blank?

    order
  end

  def express_paypal
    # session[:order] = params[:order]
    cart = @order.cart
    express_checkout_url = cart.paypal_checkout_url(
      :ip                => request.remote_ip,
      :return_url        => paypal_express_cart_index_url(:session_token => session['_csrf_token']),
      :cancel_return_url => cart_index_url
    )

    if cart.errors.empty?
      redirect_to express_checkout_url
    else
      @errors = cart.errors
      render "index"
      # render :json => cart.errors
    end
  end

  def eway_creditcard
    if giftcard_total_zero() == true
      render "giftcards"
    else
      cart  = @order.cart
      order = params[:order]
      order.delete(:cc_number)
      order.delete(:cvn)
      order[:month] = 1.month.from_now.strftime("%m").to_i
      order[:year]  = 1.month.from_now.strftime("%Y").to_i
      gon.order = order

      # render :json => @cart.all
      if cart.errors.empty?
        order = cart.create_user_and_order({:token => "", :PayerID => ""}, request.remote_ip, true)

        response = cart.eway_purchase?(ENV['EWAY_COSTUMER_ID'])
        if response.success?
          # render :json => cart.get_order.items
          order.token = response.authorization
          order.save

          # update coupon
          update_coupon_usage if session[:coupon]
          if session[:giftcard]
            totalAmount = 0
            session[:items].each do |i|
              totalAmount += i[:price].to_f
            end
            update_giftcard_usage(totalAmount, cart.get_user.id)
          end

          # send mail
          if @has_giftcards == true
            UserMailer.on_purchase_giftcard(order.id, cart.get_order.items, cart.get_password).deliver
          else
            UserMailer.on_purchase(order.id, cart.get_order.items, cart.get_password).deliver
          end
          session.delete(:coupon)
          session.delete(:giftcard)
          session.delete(:order)
          @cart.delete_all

          sign_in(:user, cart.get_user)
          # order.send_order_mail(cart.get_password)

app/views/cart/_comments.html.haml
/ col-md-4
%h3
  Order now! and get your shirt no later than
  %br/
  %span {{delivery_date | date:'MMMM dd, yyyy'}}
.checkout-orange-sticker
  %h4 BUY WITH 100% CONFIDENCE
  %ul
    %li Made By Australians, For Australians, In Australia
    %li 100% Money Back Guarantee
    %li Printed on Premium Quality Tees and Hoodies
    %li
      Got A Question? Speak to us right now on live chat below or call us on
      %strong 1300 76 65 67
.checkout-side-comment
  .comment-arrow
    .checkout-comment-container
      .checkout-comment-content
        %p “I got my hoodie today...so happy, I love it..fits perfect and so warm, great quality product too so thank you. Thanks also for emailing and keeping me informed with what was going on...great job guys n gals!”
      %img{:src => "/assets/checkout-comment-arrow-down.png"}
  %p.checkout-comment-name.commen-name-green-bg
    Vanessa Meyer
    %br/
    %span Sydney, Australia
  .comment-arrow
    .checkout-comment-container
      .checkout-comment-content
        %p Its awesome my girlfriend loves it! Thanks for the customer awesome service !!!
      %img{:src => "/assets/checkout-comment-arrow-down.png"}
  %p.checkout-comment-name.commen-name-blue-bg
    Andrew Bond
    %br/
    %span Sydney, Australia
  .comment-arrow
    .checkout-comment-container
      .checkout-comment-content
        %p Just wanted to thankyou for my hoodie as it just arrived today and I love it.
      %img{:src => "/assets/checkout-comment-arrow-down.png"}
  %p.checkout-comment-name.commen-name-orange-bg
    Kylie McTackett
    %br/
    %span Sydney, Australia
  .comment-arrow
    .checkout-comment-container
      .checkout-comment-content
        %p “I got it!!!! Thank youu guys n girls sooooo much I love it!! Deffinatly will buy more =D very happy! Thanks again!!”
      %img{:src => "/assets/checkout-comment-arrow-down.png"}
  %p.checkout-comment-name.commen-name-fb-bg
    Marlee Agius
    %br/
    %span Sydney, Australia
%p.text-center
  %img{:src => "/assets/sidebar-logo.jpg"}
/ col-md-4

app/views/cart/creditcard.html.haml
.main-content.customer-info-page{:'ng-controller' => "CartCreditCardCtrl"}
  / landing-page-content
  = form_for @order, url: checkout_cart_index_path(:payment => "CC") do |c|
    .center
      - unless @errors.empty?
        .alert.alert-danger{style: "margin-top: 15px"}
          %ul{style: "margin: 0"}
            - @errors.each do |error|
              %li= error

      .col-lg-6.col-md-6.col-sm-6.col-xs-12.customer-info-left
        %h2 Customer Information
        .form#info
          .radio
            %label{:for => "ci-email"} Email
            %input#ci-email{:placeholder => "john.doe@email.com", :type => "text", :name => "order[email]", 'ng-model'=>"checkout.email", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          %h3 Shipping Address
          .radio.fname-border
            %label{:for => "ci-fname"} First Name
            %input#ci-fname{:placeholder => "John", :type => "text", :name => "order[first_name]", 'ng-model'=>"checkout.first_name", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-lname"} Last Name
            %input#ci-lname{:placeholder => "Doe", :type => "text", :name=>"order[last_name]", 'ng-model'=>"checkout.last_name", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-address"} Address
            %input#ci-address{:autocomplete => "off", :placeholder => "123 ABC Street", :type => "text", :name=>"order[address]", 'ng-model'=>"checkout.address", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-state"} Suburb/Town
            %input#ci-town{:placeholder => "City", :type => "text", 'ng-model'=>"checkout.city", :name=>"order[city]", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-state"} State
            %input#ci-state{:placeholder => "State", :type => "text", 'ng-model'=>"checkout.state", :name=>"order[state]", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-pcode"} Postal Code
            %input#ci-pcode{:autocomplete => "off", :placeholder => "1110", :type => "text", 'ng-model' => "checkout.zip", :name => "order[zip]", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-country"} Country
            %input#ci-ccode{:type => "hidden", :name => "order[country]", 'ng-value' => "country.iso"}
            %input#ci-country{:placeholder => "Australia", :type => "text", 'ng-change' => "selectCountry(this)", 'ng-model' => "ci_country", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1.phone-border
            %label{:for => "ci-phone"} Phone
            %input#ci-phone{:placeholder => "66 7 3188 5168", :type => "text", :name => "order[phone]", "ng-model" => "checkout.phone", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          %h3 Billing & Payment
          .radio.fname-border
            %label{:for => "ci-cards"} Credit Card
            %p.cards-holder
              %img{:src => "/assets/cards.png"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-card-number"} Credit Number
            %input#ci-card-number{:placeholder => "----  ----  ----  ----", :type => "text", :name => "order[cc_number]", "ng-model" => "checkout.cc_number"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-expiry"} Expiry
            .col-lg-12.nopadding.select2
              .col-lg-6.col-md-6.col-sm-6.col-xs-6
                = select_month nil, {add_month_numbers: true}, {name: 'order[month]', "ng-model" => "checkout.month"}
              .col-lg-6.col-md-6.col-sm-6.col-xs-6
                = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: 'order[year]', "ng-model" => "checkout.year"}
              .clearfix
            .clearfix
          .radio.border-rad0.margtop-1.phone-border
            %label{:for => "ci-ccv"} CCV
            %input#ci-ccv{:placeholder => "123", :type => "text", :name => "order[cvn]", "ng-model" => "checkout.cvn"}
            .clearfix
          %input.place-order-now{:type => "submit", :value => "Place My Order Now"}
          %img{src: "/assets/sponsor-logo.png", :style => "display:block; margin: 0 auto;"}
          .clearfix
      .col-lg-6.col-md-6.col-sm-6.col-xs-12.customer-info-right
        .order-summary{'ng-cloak' => ""}
          .order-summary-header
            %h3 Order Summary
          .order-summary-body

            .item-summary{:'ng-repeat' => "item in items"}
              %a#item1-close.close-black{:href => "#", 'ng-click' => "removeItem(item.id)"}
              %ul
                %li
                  %img{:alt => "shirt", :'ng-src' => "{{item.image}}"}
                  .product-info{:style => "margin-top: 5px"}
                    %span.product-info-name
                      %strong {{item.title}}
                    %span.product-info-description
                      %select.qty{'ng-model' => "item.quantity", 'ng-options' => 'q for q in getQuantity(item)', 'ng-change' => "updateCart(item)"}
                      pc(s)
                      %select.sizes{'ng-model' => "item.size", 'ng-options' => 'size for size in getSizes(item)', 'ng-change' => "updateSize(item)"}
                      %span{"ng-if" => "!item.instock"}
                        %span -
                        %select{'ng-model' => "item.category", 'ng-options' => 'category.name for category in item.categories', 'ng-change' => "updateCategory(item)", :style => "max-width: 130px"}
                      %span{"ng-if" => "item.instock"}
                        = "- {{item.info.type}}"
                  %span.shirt-value {{item.info.amount * item.quantity  | currency:"$"}}
                  .clearfix
              %span.arrive-due-date Your order is due to arrive on {{delivery_date | date:'MMMM dd, yyyy'}}

            .discount
              %a.discount-link{:href => "#", 'ng-show' => "!show_coupon", 'ng-click' => "toggleCoupon()"} Have a discount code? Click here to enter it
              .discount-form#coupon-discount-form{'ng-show' => "show_coupon"}
                %label{:for => "checkout_discount_code"} Discount
                %input#checkout_discount_code{'ng-model' => "coupon.code", :placeholder => "......", :size => "30", :type => "text", :name => "order[coupon_code]"}
                %input.discount-btn{:name => "commit", :type => "button", :value => "Apply", 'ng-click' => "applyCoupon()"}
            .order-summary-section
              %ul
                %li
                  Subtotal
                  %span {{subtotal | currency:"$"}}
                %li{'ng-if' => "coupon.percent > 0"}
                  Coupon Discount
                  %span {{coupon.percent}}%
                %li
                  Shipping
                  %span {{shipping | currency:"$"}}
                %li
                  Total
                  %span {{shipping + subtotal | currency:"$"}}
            .payment-due
              %p
                Payment Due
                %span.due-value
                  %span.currency aud
                  {{shipping + subtotal - coupon.discount | currency:"$"}}
      .clearfix

  %script{:src => "//expresscapture.datatoolscloud.net.au/js/expresscapture-2.20.min.js?key=UE93-DR37-AT75-PU78", :type => "text/javascript"}
  %link{:href => "//expresscapture.datatoolscloud.net.au/css/expresscapture-2.20.min.css?key=UE93-DR37-AT75-PU78", :rel => "stylesheet", :type => "text/css"}

app/views/cart/giftcards.haml
.main-content.customer-info-page{:'ng-controller' => "GiftCardCtrl"}
  / landing-page-content
  = form_for @order, url: giftcard_express_cart_index_path() do |c|
    .center
      - unless @errors.empty?
        .alert.alert-danger{style: "margin-top: 15px"}
          %ul{style: "margin: 0"}
            - @errors.each do |error|
              %li= error

      .col-lg-6.col-md-6.col-sm-6.col-xs-12.customer-info-left
        %h2 Customer Information
        .form
          .radio
            %label{:for => "ci-email"} Email
            %input#ci-email{:placeholder => "john.doe@email.com", :type => "text", :name => "order[email]", 'ng-model'=>"checkout.email", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          %h3 Shipping Address
          .radio.fname-border
            %label{:for => "ci-fname"} First Name
            %input#ci-fname{:placeholder => "John", :type => "text", :name => "order[first_name]", 'ng-model'=>"checkout.first_name", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-lname"} Last Name
            %input#ci-lname{:placeholder => "Doe", :type => "text", :name=>"order[last_name]", 'ng-model'=>"checkout.last_name", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-address"} Address
            %input#ci-address{:autocomplete => "off", :placeholder => "123 ABC Street", :type => "text", :name=>"order[address]", 'ng-model'=>"checkout.address", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-state"} Suburb/Town
            %input#ci-town{:placeholder => "City", :type => "text", 'ng-model'=>"checkout.city", :name=>"order[city]", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-state"} State
            %input#ci-state{:placeholder => "State", :type => "text", 'ng-model'=>"checkout.state", :name=>"order[state]", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-pcode"} Postal Code
            %input#ci-pcode{:autocomplete => "off", :placeholder => "1110", :type => "text", 'ng-model' => "checkout.zip", :name => "order[zip]", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-country"} Country
            %input#ci-ccode{:type => "hidden", :name => "order[country]", 'ng-value' => "country.iso"}
            %input#ci-country{:placeholder => "Australia", :type => "text", 'ng-change' => "selectCountry(this)", 'ng-model' => "ci_country", 'ng-blur'=>"fieldBlur()"}
            .clearfix
          .radio.border-rad0.margtop-1.phone-border
            %label{:for => "ci-phone"} Phone
            %input#ci-phone{:placeholder => "Optional", :type => "text", :name => "order[phone]", "ng-model" => "checkout.phone", 'ng-blur'=>"fieldBlur()"}
            .clearfix

          %input.place-order-now{:type => "submit", :value => "Place My Order Now"}
          .clearfix
      .col-lg-6.col-md-6.col-sm-6.col-xs-12.customer-info-right
        .order-summary{'ng-cloak' => ""}
          .order-summary-header
            %h3 Order Summary
          .order-summary-body

            .item-summary{:'ng-repeat' => "item in items"}
              %ul
                %li
                  %img{:alt => "shirt", :'ng-src' => "{{item.image}}"}
                  .product-info{:style => "margin-top: 5px"}
                    %span.product-info-name
                      %strong {{item.title}}
                    %span.product-info-description
                      {{item.quantity}}
                      pc(s)
                      {{item.size}}
                      = "- {{item.info.type}}"
                  %span.shirt-value {{item.info.amount * item.quantity  | currency:"$"}}
                  .clearfix
              %span.arrive-due-date Your order is due to arrive on {{delivery_date | date:'MMMM dd, yyyy'}}


            .order-summary-section
              %ul
                %li
                  Subtotal
                  %span {{subtotal | currency:"$"}}

                %li{'ng-if' => "!giftcard.error"}
                  Giftcard Discount
                  %span {{giftcard.amount | currency: "$"}}
                %li
                  Shipping
                  %span {{shipping | currency:"$"}}
                %li
                  Total
                  %span {{shipping + subtotal | currency:"$"}}
            .payment-due
              %p
                Payment Due
                %span.due-value
                  %span.currency aud

                  {{TotalwithGiftCards(shipping,subtotal, giftcard.amount) | currency:"$"}}
      .clearfix