config/routes.rb
Fantees::Application.routes.draw do
  root :to => 'home#index'

  devise_for :users, :skip => [:registrations]

  get "dashboard", :controller => 'dashboard/home', :action => :index
  namespace :dashboard do
    resources :users, :only => [:show, :update]
    resources :giftcards, :only => [:index, :show ]
    resources :orders, :only => [:index, :show, :update] do

      member do
        get :ordered_products
      end
      collection do
        get :latest
      end
    end
  end

  resources :products, :only => [:index, :show] do
    collection do
      get  :checkout
      post :set_checkout_session
      post :paypal_checkout
      post :eway_checkout
      post :order_checkout
      get  "api/:slug", :action => :product_info
      get  "upsell/:key", :action => :product_upsell
      # get :success, :action => :return_url
    end
    member do
      get :success, :action => :return_url
    end
  end
  # get "product_info/:slug", :controller => :products, :action => :product_info
  get "products/:id/:url", :controller => "products", :action => :show

  resources :categories, :only => [:index, :show]
  resources :orders, :only => [:show, :create] do
    member do
      get :success, :action => :show
    end
    collection do
      post :update_unfinished, :action => :update_unfinished_order
    end
  end
  get "order/rebuild/:tracking_id", :controller => :orders, :action => :rebuild

  # checkout pages
  resources :cart, :only => [:index, :create, :update, :destroy] do
    collection do
      get :all
      get :creditcard
      get :paypal_express
      get :checkout
      post :checkout
      get :giftcards
      post :giftcard_express

    end
  end
  get "cart/rebuild/:tracking_id", :controller => :cart, :action => :rebuild

  post "pages/send_contact_us"
  get "contact-us",           :controller => :pages, :action => :contact_us
  get "about-us",             :controller => :pages, :action => :about_us
  get "faq",                  :controller => :pages, :action => :faq
  get "privacy-policy",       :controller => :pages, :action => :privacy
  get "terms-of-service",     :controller => :pages, :action => :terms
  get "shipping",             :controller => :pages, :action => :shipping
  get "returns-exchanges",    :controller => :pages, :action => :returns_exchanges
  get "sizing",               :controller => :pages, :action => :sizing
  get "process",              :controller => :pages, :action => :processing
  get "pinterest-56764.html", :controller => :pages, :action => :pinterest
  get "win",                  :controller => :pages, :action => :win
  get "coupons/:code",        :controller => :coupons, :action => :show
  get "giftcards/:code",      :controller => :giftcards, :action => :show
  get "bundle",               :controller => :home, :action => :bundled
  get "giftcards",            :controller => :home, :action => :giftcards
  get "home/search",               :controller => :home, :action => :search
  get "search/name",          :controller => :products, :action => :name_search
  post "search/name/notify",  :controller => :products, :action => :name_search_notify

  get "render_email_pixel/:time_frame",   :controller => :mail_tracker, :action => :render_pixel, :as => :render_email_pixel

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'f@nt33s'
  end
  mount Sidekiq::Web => '/sidekiq'

  get "fathersday",           :controller => :home, :action => :custom_url
  get "pet-rescue",           :controller => :home, :action => :custom_url
  get "fishing-shirts",       :controller => :home, :action => :fishing_shirts
  get "nurse-shirts",         :controller => :home, :action => :nurse_shirts
  get "mechanic-shirts",      :controller => :home, :action => :mechanic_shirts
  get "sprint-car-shirts",    :controller => :home, :action => :sprint_car_shirts
  get "firefighter-shirts",   :controller => :home, :action => :firefighter_shirts
  get "dog-shirts",           :controller => :home, :action => :dog_shirts
  get "builder-shirts",       :controller => :home, :action => :builder_shirts
  get "electrician-shirts",   :controller => :home, :action => :electrician_shirts
  get "dirt-bike-shirts",     :controller => :home, :action => :dirt_bike_shirts
  get "british-comedy-shirts",:controller => :home, :action => :british_comedy_shirts
  get "beard-shirts",         :controller => :home, :action => :beard_shirts
  get "drag-racing-shirts",   :controller => :home, :action => :drag_racing_shirts
  get "camping-shirts",       :controller => :home, :action => :camping_shirts
  get "football-shirts",      :controller => :home, :action => :football_shirts
  get "torana-shirts",        :controller => :home, :action => :torana_shirts
  get "rum-shirts",           :controller => :home, :action => :rum_shirts
  get "wine-shirts",          :controller => :home, :action => :wine_shirts
  get "v8-shirts",            :controller => :home, :action => :v8_shirts
  get "army-shirts",          :controller => :home, :action => :army_shirts
  get "burnout-shirts",       :controller => :home, :action => :burnout_shirts
  get "farmanimalrescue",     :controller => :home, :action => :farmanimalrescue_shirts

  get ":slug",                :controller => "products", :action => :show
  
end

app/controllers/products_controller.rb
include ActionView::Helpers::NumberHelper
class ProductsController < ApplicationController
  before_filter :check_product, :only => [:paypal_checkout, :set_checkout_session, :checkout]

  def index
    @products = Product.where(active: true)
    respond_to do |format|
      format.xml
    end
  end

  def name_search
    unless params[:q].nil?
      keyword = [params[:q], params[:s]].join(" ")
      searches = Product.search_by_tags(keyword)
      if searches.empty?
        @s = Search.new
        @s.name = keyword
        @s.fname = params[:q]
        @s.lname = params[:s]
        @s.save
      else
        @product = searches.first
      end
    end
  end

  def name_search_notify
    @notify = true
    @search = Search.find(params[:i])
    @search.email = params[:email]
    @search.save
    render "name_search"
  end

  def show

    session.delete(:rebuild)
    session.delete(:rebuild_time_frame)

    @product = @website.products.where(:slug => params[:slug]).first

    unless @product.nil?
      # puts @cart.inspect
      # render :json => {cart: @cart}
      @fb_og_image = @product.product_images.sample.product_image(:medium)
      @sold        = @product.total_sold
      start_num    = @product.start_number ? @product.start_number : 0
      @sales       = start_num + @sold
      # @categories  = Category.where(:id => @product.settings(:options).categories).where(:active => true)
      @error       = params[:error] ? true : false
      @order_err   = params[:o] ? true : false
      @title       = @product.title

      gon.category_id = params[:cid].nil? ? nil : params[:cid]
      # gon.current_user = current_user
      # gon.product      = @product
      # gon.gallery      = @product.gallery
      # gon.prices       = @product.settings(:options).prices
      # gon.categories   = @categories
      # gon.stocks       = @product.stocks if @product.status != 0

      # delivery_date = @product.date + 14.days
      # if @product.status == 2
      #   # if have stocks
      #   delivery = DeliveryService.new(2, Time.now)
      #   delivery_date = delivery.bussiness_days
      # end

      # gon.delivery_date = delivery_date.strftime("%b %d, %Y")
    else
      redirect_to "https://campaigns.fantees.com.au/#{params[:slug]}"
      # redirect_to root_path
      # respond_to do |format|
      #   format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      #   format.xml  { head :not_found }
      #   format.any  { head :not_found }
      # end
    end
  end

  def product_info
    product = @website.products.where(:slug => params[:slug]).first
    unless product.nil?
      # delivery_date = product.date + 14.days
      delivery_date = product.date + 9.days
      if product.status == 2
        # if have stocks
        # delivery = DeliveryService.new(2, Time.now)
        # delivery_date = delivery.bussiness_days
        delivery_date = Time.now.beginning_of_day + 4.days
      elsif product.status == 1
        delivery_date = Time.now.beginning_of_day + 12.days
      end

      if product.status == 2
        international = Time.now.beginning_of_day + 10.days
        domestic      = Time.now.beginning_of_day + 4.days
      elsif product.status == 1
        international = Time.now.beginning_of_day + 14.days
        # domestic      = Time.now.beginning_of_day + 10.days
        domestic      = Time.now.beginning_of_day + 9.days
      else
        international = product.date + 14.days
        # domestic      = product.date + 10.days
        domestic      = product.date + 9.days
      end

      render :json => {
        product: product,
        gallery: product.gallery,
        prices:  product.settings(:options).prices,
        stocks:  product.status != 0 ? product.stocks : nil,
        delivery_date: delivery_date.strftime("%b %d, %Y"),
        international: international.strftime("%b %d, %Y"),
        domestic: domestic.strftime("%b %d, %Y"),
        categories: Category.where(:id => product.settings(:options).categories).where(:active => true)
      }
    else
      render :json => product
    end
  end

  def product_upsell
    begin
      product = Product.where(:slug => params[:key]).first
      tags = JSON.parse product.tags

      # puts "tag awa", product.tags
      search = ''
      tags.each  do |tag|
        search = "#{search} #{tag['text']}"
      end
      products = Product.where((['products.tags LIKE ?'] * search.split.length).join(' OR '), *search.split(" ").map{|keyword| "%\"#{keyword}\%"}).limit(3)

      allData = []

      products.each do |p|
        # delivery_date = p.date + 14.days
        delivery_date = p.date + 9.days
        if p.status == 2
          # if have stocks
          # delivery = DeliveryService.new(2, Time.now)
          # delivery_date = delivery.bussiness_days
          delivery_date = Time.now.beginning_of_day + 4.days
        elsif p.status == 1
          delivery_date = Time.now.beginning_of_day + 12.days
        end
        allData << {
          id: p.id,
          product: p,
          gallery: p.gallery,
          prices:  p.settings(:options).prices,
          stocks:  p.status != 0 ? p.stocks : nil,
          delivery_date: delivery_date.strftime("%b %d, %Y"),
          categories: Category.where(:id => p.settings(:options).categories).where(:active => true)
        }
      end
    rescue
      allData = []
    end

    render :json => allData

    # render :json => products
  end

  def giftcards
    @product = @website.products.where(:slug => params[:slug]).first

    unless @product.nil?
      # puts @cart.inspect
      # render :json => {cart: @cart}
      @fb_og_image = @product.product_images.sample.product_image(:medium)
      @sold        = @product.total_sold
      start_num    = @product.start_number ? @product.start_number : 0
      @sales       = start_num + @sold
      @categories  = Category.where(:id => @product.settings(:options).categories).where(:active => true)
      @error       = params[:error] ? true : false
      @order_err   = params[:o] ? true : false

      gon.current_user = current_user
      gon.product      = @product
      gon.gallery      = @product.gallery
      gon.prices       = @product.settings(:options).prices
      gon.categories   = @categories
      gon.stocks       = @product.stocks if @product.status != 0

      # delivery_date = @product.date + 14.days
      delivery_date = @product.date + 9.days
      if @product.status == 2
        # if have stocks
        # delivery = DeliveryService.new(2, Time.now)
        # delivery_date = delivery.bussiness_days
        delivery_date = Time.now.beginning_of_day + 4.days
      elsif @product.status == 1
        delivery_date = Time.now.beginning_of_day + 12.days
      end

      gon.delivery_date = delivery_date.strftime("%b %d, %Y")
    else
      redirect_to root_path
    end
  end

  def paypal_checkout

    begin
      # puts params.inspect
      product  = Product.find(params[:product_id])
      redirect_to root_path unless @product.active

      qty      = 0
      key      = 0
      subtotal = 0
      shipping = 0
      items    = []
      session[:orders] = []
      params[:orders][:qty].each do |o|
        category_id = params[:orders][:styles][key]
        size  = params[:orders][:sizes][key]
        style = Category.find(category_id)
        info  = product.price_and_profit_of_style(category_id)

        qty      += o.to_i
        subtotal += o.to_i * info[:amount].to_f
        shipping = info[:postage].to_f if info[:postage] && info[:postage] > shipping

        session[:orders] << {:category_id => style.id, :quantity => o.to_i, :size => size, :price => info[:amount]}
        items << {:name => product.title, :quantity => o.to_i, :description => "#{size} #{style.name} type_id: #{style.id}", :amount => (info[:amount]*100)}

        key += 1
      end

      # total = qty * product.price
      subtotal = subtotal * 100
      shipping = product.free_shipping > qty ? shipping * 100 : 0
      total    = subtotal + shipping
      # total = subtotal
      response = EXPRESS_GATEWAY.setup_purchase(total.round,
        :subtotal          => subtotal.round,
        :shipping          => shipping.round,
        :handling          => 0,
        :tax               => 0,
        :items             => items,
        :ip                => request.remote_ip,
        :currency          => 'AUD',
        :return_url        => success_product_url(product.id),
        :cancel_return_url => "#{root_url}/#{product.slug}"
      )

      # render :json => {response: response, shipping: shipping, :subtotal => subtotal, items: items}
      redirect_to "#{EXPRESS_GATEWAY.redirect_url_for(response.token)}&useraction=commit"


    rescue Exception => exc
       error_msg = "Message for the log file: #{exc.message}"
       UserMailer.delay.send_error_logs('matt.stenning@graphicsadmin.com', error_msg)
       UserMailer.delay.send_error_logs('rick@fantees.com.au', error_msg)
       # redirect_to root_path
    end

  end

  # def return_url
  #   orders = []
  #   if session[:orders].nil?
  #     gateway = EXPRESS_GATEWAY.details_for(params[:token])
  #     gateway.params["PaymentDetails"]["PaymentDetailsItem"].each do |o|
  #       desc = o["Description"].split(" ")
  #       amt  = o["Amount"].to_f
  #       qty  = o["Quantity"]
  #       orders << {category_id: desc.last.to_i, quantity: qty.to_i, size: desc.first, price: amt}
  #     end
  #   else
  #     orders = session[:orders]
  #   end

  #   unless orders.blank?
  #     params[:ip] = request.remote_ip
  #     # paypal      = PaypalCheckout.new(params, session)
  #     paypal      = PaypalCheckout.new(params, session[:orders])
  #     product     = Product.find(params[:id])
  #     order       = Order.find_by_token(params["token"])
  #     check_order = paypal.check_orders

  #     # render :json => {paypal: paypal, orders: paypal.check_orders}
  #     if order.nil? && check_order

app/views/products/_pre_footer.html.haml
#pre-footer-wrapper{style: "min-height: 217px;"}
  .container
    .row
      .col-md-6
        %p.guarantee-wrap
          %span.guarantee We guarantee 100% satisfaction
          %br
          If you don't absolutely love your print, we'll take it back.
          = link_to "Learn more", "#"
        - if controller_name == "products"
          - if @product.active
            = link_to "Buy It Now", "#", {class: "btn-sm-custom", :'ng-click' => "openModal(product)"}
        - elsif controller_name == "home"
          = link_to "Contact Us", "/contact-us", {class: "btn-sm-custom"}
      .col-md-6
        .row
          .col-xs-6.col-md-6.learn-more
            %span.dark Learn More
            %ul
              %li
                = link_to "About us", "/about-us"
              %li
                = link_to "FAQ", "/faq"
              %li
                = link_to "Contact us", "/contact-us"

          .col-xs-6.col-md-6.your-account
            %span.dark Your Account
            %ul
              %li
                = link_to "Log In", new_user_session_path
              %li
                = link_to "Track An Order", "/dashboard/#/orders"

app/views/products/checkout.html.haml
%div{:'ng-controller' => "CheckoutCtrl"}
	- real_total = @total + @shipping

	.content-checkout
		.container.check-out-grey-bg
			.row
				- if @coupon_err
					.alert.alert-danger{style: "margin: 10px"}
						Invalid Coupon Code.

				.col-md-8.checkout-leftcontent
					.checkout-order-details

						- flash.each do |name,msg|
							%div{class: "alert alert-#{name == :notice ? "success" : "danger"}"}
								- msgs = msg.split(",")
								%ul{style: "margin-top:0 !important;"}
									- msgs.each do |m|
										%li
											= m.strip

						%h2 Order Details
						.spacer

						-# %form{:role => 'form'}
						= form_for @order, url: order_checkout_products_path do |c|
							%input{ :type=>"hidden",:name=>"product_id",:value=>"#{@product.id}" }

							- @pending_orders.each do |o|
								.order-sample-container
									-# %a{:href=>"#"}
									-# 	%img.x-btn{:src=>"/assets/x-btn.png"}

									.col-md-2.order-img-container.text-center
										%img{:src=>"#{o[:image]}"}

									.col-md-10
										%h3
											= o[:name]
										%p
											You have ordered a
											%strong
												= succeed ',' do
													= o[:style]
											in size:
											- if @product.status != Product::CAMPAIGN
												%input{:type=>"hidden",:name=>"size[]",:value=>"#{o[:size]}"}
												= o[:size]

											-# = o[:description].html_safe
										-# %p.save Save $10 on every shirt you buy!
										%input{:type=>"hidden",:name=>"qty[]",:value=>"#{o[:qty]}"}
										%input{:type=>"hidden",:name=>"cat_ids[]",:value=>"#{o[:category_id]}"}
										- if @product.status == Product::CAMPAIGN
											%select.small-select{:name=>"size[]", :style => "margin:0 !important;" }
												- o[:sizes].each do |s|
													- if s == o[:size]
														%option{:value=>"#{s}", :selected=>"selected"} #{s}
													- else
														%option{:value=>"#{s}"} #{s}

										%p.shirt-price
											= o[:price]

									.clearfix

							%p.shipping-fee
								Shipping fee
								%span
									{{shipping_fee | currency:"$"}}
							%p.details-total
								TOTAL:
								%span
									{{total | currency:"$"}}

							.checkout-shipping-information
								%h2 Shipping Information
								%p.field-note All Fields Are Required
								.spacer
								.checkout-shipping-form-container
									.col-md-6
										%p First Name
										%input{ :tabindex=>1, :type => "text", :name => "first_name", :placeholder => "Enter your first name", :'ng-model'=>"checkout.first_name" }
										.spacer15
										%p Last Name
										%input{ :tabindex=>2, :type=>"text", :name=>"last_name", :placeholder=>"Enter your last name", :'ng-model'=>"checkout.last_name" }
										.spacer15
										%p Email Address
										%input{:tabindex=>3, :type => "email", :name => "email", :placeholder => "Enter your email address", :'ng-model'=>"checkout.email" }
										.spacer15
										%p Phone Number
										%input{:tabindex=>4, :type=>"text", :name=>"phone", :placeholder=>"Enter your phone number", :'ng-model'=>"checkout.phone" }
										.spacer15

									.col-md-6


										%p Street Address
										%input{:tabindex=>5,:name=>"address", :placeholder=>"Enter your address", :type=>"text",:'ng-model'=>"checkout.address" }
										-# %input#autocomplete{:tabindex=>5,:name=>"address", :placeholder=>"Enter your address", :onFocus=>"geolocate()", :type=>"text",:'ng-model'=>"checkout.street_address" }
										-# %input.field#subpremise{:name=>"subpremise", :disabled=>"true", :type=>"text", :style=>"display:none;" }
										-# %input.field#street_number{:name=>"street_number", :disabled=>"true", :type=>"text", :style=>"display:none;" }
										-# %input.field#route{:name=>"route", :disabled=>"true", :type=>"text", :style=>"display:none;" }
										.spacer15

										%p Suburb / Town
										%input.field#locality{:tabindex=>6,:'ng-model'=>"checkout.city",:name=>"city", :type=>"text"}
										.spacer15

										.col-md-6.no-padding-left
											%p State
											%input.field#administrative_area_level_1{:tabindex=>7,:'ng-model'=>"checkout.state", :name=>"state", :type=>"text"}

										.col-md-6.no-padding-right
											%p Postal Code
											%input.field#postal_code{:tabindex=>8,:'ng-model'=>"checkout.zip",:name=>"zip", :type=>"text" }
										.clearfix
										.spacer15

										%p Country
										%input{ :type=>"hidden",:name=>"country",:value=>"{{checkout.country}}"}
										/ %input{ :type=>"text", :value=>"{{country.name}}", :disabled=>"disabled"}
										= select_tag :select, "", {:'ng-model' => "country", :'ng-options' => 'c.name for c in countries', :'ng-change' => "selectCountry(this)"}

									.clearfix

							.checkout-payment-option
								.spacer
								.radio01.radioCurrent
									%label
										%input#optionsRadios1{:tabindex=>9, :type=>"radio", :name=>"optionsRadios", :value=>"creditcard", :checked=>"checked", :'ng-click' => "selectPayment('CC')" }
										%img{:src=>"/assets/cc.png"}

								/ 	%label{style: "width: 160px"}
								/ 		%input.btn-sm-custom-pop{type: "button", name: "add_coupon", value: "Add A Coupon", :'ng-click' => "addCoupon()"}

								/ %div{:'ng-show' => 'coupons.length > 0'}
								/ 	.spacer
								/ 	%h3 Coupon Codes
								/ 	.col-md-6
								/ 		.row{style: "padding: 5px 15px", :'ng-repeat' => "coupon in coupons track by $index"}
								/ 			%input{type: "text", name: "coupon[]", placeholder: "Coupon Code # {{$index + 1}}", style: "width: 95%", :'ng-model' => "coupon.value"}
								/ 			%a{style: "cursor: pointer", :'ng-click' => "removeCoupon($index)"}
								/ 				%img{src: "/assets/rex-x.png"}

								/ 	.col-md-6
								/ 		&nbsp;

								/ 	.clearfix

							.checkout-credit-card
								%h2 Credit card information
								%p.field-note All Fields Are Required
								.spacer
								.col-md-6
									%p Credit card number
									%input{:'ng-model'=>"checkout.cc_number", :type=>"text", :name=>"cc_number", :value=>"" }

								.col-md-3
									%p Expiration date
									%input.exp-date{:'ng-model'=>"checkout.month",:type=>"text",:name=>"month",:placeholder=>"MM"}
									%span.date-dash -
									%input.exp-date{:'ng-model'=>"checkout.year",:type=>"text",:name=>"year",:placeholder=>"YY"}
									.clearfix
								.col-md-3
									%p CVV code
									%input{:'ng-model'=>"checkout.cvn",:type=>"text",:name=>"cvn",:value=>""}

								.clearfix
								.spacer

								%p{style: "padding: 0 15px"}
									%a{style: "cursor: pointer; color: #ccc", :'ng-click' => "toggleCoupon()"} Have a coupon code?

								%p{style: "padding: 0 15px", :'ng-show' => "show_coupon"}
									%input{type: "text", name: "coupon", placeholder: "Coupon Code", style: "width: 50%", :'ng-model' => "coupon.code", :'ng-class' => "coupon.txtClass"}
									%input{type: "hidden", name: "check_coupon", :'ng-model' => "coupon.checked"}
									%input.checkout-coupon-btn{type: "button", name: "button", :'ng-click' => "applyCoupon()", :'ng-class' => "coupon.class", :'ng-value' => "coupon.btn"}
									/ %span#coupon-desc{style: "border: 1px solid #d3d3d3; margin-left: -4px; padding: 3px 6px; width: 50%; display: inline-block"}
									/ 	%i{style: "color: #555"} {{coupon.description}}
								.clearfix

								.col-md-12
									.checkout-total
										%p.total-price
											Your Order total :
											%span
												{{total - coupon.discount | currency:"$"}}
										%p.arrive-date
											Your order will arrive No Later than:
											%span
												= @delivery_date.strftime("%b %d, %Y")
										.clearfix
									%input{:type=>"hidden",:name=>"mode",:value=>"credit"}
									%input{:type=>"submit",:value=>"Place your order now",:name=>"Submit",:'ng-click'=>"submitCheckout()"}

								.spacer15
								%p.text-center
									%img{:src=>"/assets/sponsor-logo.png"}

							/paypal
							.checkout-credit-card-paypal{:style=>"display:none;"}
								%h2 You will be sent to PayPal website for secure payment
								.clearfix
								.spacer
								.col-md-12
									.checkout-total
										%p.total-price
											Your Order total :
											%span
												= number_to_currency(real_total)
										%p.arrive-date
											Your order will arrive No Later than:
											%span
												= @delivery_date.strftime("%b %d, %Y")
										.clearfix
									.spacer
									%input{:name=>"paypal",:type=>"submit",:value=>"Place your order now",:'ng-click'=>"submitCheckout()"}
									/%a.link-to-paypal{:href=>"#",:'ng-click'=>"submitCheckout()"} Place Your Order Now
								.spacer15
								%p.text-center
									%img{:src=>"/assets/bdg_secured_by_pp_2line.png"}


				.col-md-4.sidebar-checkout
					%h3
						Order now! and get your shirt no later than
						%br
						%span
							= @delivery_date.strftime("%B %d, %Y")
					.checkout-orange-sticker
						%h4 BUY WITH 100% CONFIDENCE
						%ul
							%li Made By Australians, For Australians, In Australia
							%li 100% Money Back Guarantee
							%li Printed on Premium Quality Tees and Hoodies
							%li
								Got A Question? Speak to us right now on live chat below or call us on
								%strong 1300 76 65 67
					.checkout-side-comment
						.comment-arrow
							.checkout-comment-container
								.checkout-comment-content
									%p “I got my hoodie today...so happy, I love it..fits perfect and so warm, great quality product too so thank you. Thanks also for emailing and keeping me informed with what was going on...great job guys n gals!”
								%img{:src=>"/assets/checkout-comment-arrow-down.png"}

						%p.checkout-comment-name.commen-name-green-bg
							Vanessa Meyer
							%br
							%span Sydney, Australia

						.comment-arrow
							.checkout-comment-container
								.checkout-comment-content
									%p Its awesome my girlfriend loves it! Thanks for the customer awesome service !!!
								%img{:src=>"/assets/checkout-comment-arrow-down.png"}
						%p.checkout-comment-name.commen-name-blue-bg
							Andrew Bond
							%br
							%span Sydney, Australia

						.comment-arrow
							.checkout-comment-container
								.checkout-comment-content
									%p Just wanted to thankyou for my hoodie as it just arrived today and I love it.
								%img{:src=>"/assets/checkout-comment-arrow-down.png"}
						%p.checkout-comment-name.commen-name-orange-bg
							Kylie McTackett
							%br
							%span Sydney, Australia

						.comment-arrow
							.checkout-comment-container
								.checkout-comment-content
									%p “I got it!!!! Thank youu guys n girls sooooo much I love it!! Deffinatly will buy more =D very happy! Thanks again!!”
								%img{:src=>"/assets/checkout-comment-arrow-down.png"}
						%p.checkout-comment-name.commen-name-fb-bg
							Marlee Agius
							%br
							%span Sydney, Australia

					%p.text-center
						%img{:src=>"/assets/sidebar-logo.jpg"}

	/= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"
	/= javascript_include_tag "checkout.js"



= rejoiner_tracking

:javascript

	var orders = gon.params.orders;

	_rejoiner.push(['setCartData',{
		value: gon.total,
		totalItems: orders.styles.length,
		returnUrl: gon.root_url + 'order/rebuild/' + gon.tracking_id
	}]);

	var i = 0;
	for(i=0;i<orders.styles.length;i++){
		_rejoiner.push(['setCartItem',{
			product_id: gon.product.id,
			name: gon.product.title,
			item_qty: parseInt(orders.qty[i]),
			category: orders.styles[i],
			image_url: gon.product_image,
			price: "$" + orders.price[i] + ".00"
		}]);
	}

app/views/products/index.html.haml
%h1 Products#index
%p Find me in app/views/products/index.html.haml

app/views/products/index.xml.erb
<?xml version="1.0"?>
<rss xmlns:g="http://base.google.com/ns/1.0" version="2.0">
  <channel>
    <title>Fantees</title>
    <link><%= "https://#{ENV['BASE_URL']}" %></link>
    <description>We are the only online store you need for all your fan based apparel. Sport, Jobs, Cars anything that you're a fan of we have the perfect design for you!</description>
    <% @products.each do |product| %>
      <% product.product_images.each do |ps| %>
        <%- product.settings(:options).prices.each do |pr| %>
          <%- if !ps.category.nil? && pr[:category_id] == ps.category.id %>
            <item>

              <title><%= product.title %> - <%= ps.category.name %></title>
              <link><%= "#{root_url}/#{product.slug}" %></link>
              <description><%= strip_tags product.description %></description>
              <g:id><%= product.id %></g:id>
              <g:condition><%= product.condition %></g:condition>
              <g:price><%= number_to_currency pr[:amount], unit: "" %> AUS</g:price>
              <g:availability><%= product.availability %></g:availability>
              <g:image_link><%= ps.product_image %></g:image_link>

              <g:google_product_category><%= product.product_category %></g:google_product_category>


              <g:item_group_id>G<%= product.id %></g:item_group_id>


              <g:brand><%= product.brand %></g:brand>
              <g:mpn><%= product.id %></g:mpn>
            </item>
          <% end %>    
        <% end %>
      <% end %>
    <% end %>

  </channel>
</rss>